language: node_js
node_js:  
  - node #latest stable version

install: npm install

script:
  - npm run build
  - npm prune --production

before_deploy:
  - zip -qr code.zip node_modules build package.json package-lock.json

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "ap-southeast-1"
    app: "app-name"
    env: "environment-name"
    bucket_name: "bucket_name"
    zip_file: code.zip
